service:
  name: demo-appsync
# app and org for use with dashboard.serverless.com
app: demo-appsync
org: willpeixoto

plugins:
  - serverless-webpack
  - serverless-plugin-additional-stacks

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  default: ${self:service.name}-${self:provider.stage}
  account: ${file(./env/env.${self:provider.stage}.yml):account.id}
  dynamo: ${file(./env/env.${self:provider.stage}.yml):tables}
  dynamodbStackName: ${self:custom.default}-dynamodb
  cognitoStackName: ${self:custom.default}-cognito
  
  additionalStacks:    
    dynamodbResourcesStack:
      Deploy: Before
      StackName: ${self:custom.dynamodbStackName}
      Resources: ${file(./resources/dynamodb.yml)}
    #because appSync we need to add cognito support for our api, and we need to expose te output
    cognitoResourcesStack:
      Deploy: Before
      StackName: ${self:custom.cognitoStackName}
      Resources: ${file(./resources/cognito.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  timeout: 90
  stage: ${opt:stage, "dev"}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

# resources: ${file(./resources/resources.yml)}