#Lets create a user poll to use with our application
CognitoUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
        # Generate a name based on the stage
      UserPoolName: ${self:custom.default}-userpool
        # Set email as an alias
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: nickname
          AttributeDataType: String
          Mutable: true
          Required: false

CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:custom.default}-user-pool-client
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false

# The federated identity for our user pool to auth with
CognitoIdentityPool:
  Type: AWS::Cognito::IdentityPool
  Properties:
    # Generate a name based on the stack-stage
    IdentityPoolName: ${self:custom.default}IdentityPool
    # Don't allow unathenticated users
    AllowUnauthenticatedIdentities: false
    # Link to our User Pool
    CognitoIdentityProviders:
      - ClientId:
          Ref: CognitoUserPoolClient
        ProviderName:
          Fn::GetAtt: [ "CognitoUserPool", "ProviderName" ]
          
# IAM roles
CognitoIdentityPoolRoles:
  Type: AWS::Cognito::IdentityPoolRoleAttachment
  Properties:
    IdentityPoolId:
      Ref: CognitoIdentityPool
    Roles:
      authenticated:
        Fn::GetAtt: [CognitoAuthRole, Arn]
        
# IAM role used for authenticated users
CognitoAuthRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: ${self:custom.role.cognito.auth.name}
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: 'Allow'
          Principal:
            Federated: 'cognito-identity.amazonaws.com'
          Action:
            - 'sts:AssumeRoleWithWebIdentity'
          Condition:
            StringEquals:
              'cognito-identity.amazonaws.com:aud':
                Ref: CognitoIdentityPool
            'ForAnyValue:StringLike':
              'cognito-identity.amazonaws.com:amr': authenticated
    Policies:
      - PolicyName: 'CognitoAuthorizedPolicy'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Action:
                - 'mobileanalytics:PutEvents'
                - 'cognito-sync:*'
                - 'cognito-identity:*'
              Resource: '*'
            
            # Allow users to invoke our API
            - Effect: 'Allow'
              Action:
                - 'execute-api:Invoke'
              Resource:
                Fn::Join:
                  - ''
                  -
                    - 'arn:aws:execute-api:'
                    - Ref: AWS::Region
                    - ':'
                    - Ref: AWS::AccountId
                    - ':'
                    - Ref: ApiGatewayRestApi
                    - '/*'
            - Effect: "Allow"
              Action:
                - appsync:GraphQL              
              Resource:
                - '*'

# Create a role for unauthorized access to AWS resources. Very limited access. Only allows users in the previously created Identity Pool
# CognitoUnAuthorizedRole:
#   Type: "AWS::IAM::Role"
#   Properties:
#     RoleName: ${self:custom.role.cognito.unAuth.name}
#     AssumeRolePolicyDocument:
#       Version: "2012-10-17"
#       Statement:
#         - Effect: "Allow"
#           Principal:
#             Federated: "cognito-identity.amazonaws.com"
#           Action:
#             - "sts:AssumeRoleWithWebIdentity"
#           Condition:
#             StringEquals:
#               "cognito-identity.amazonaws.com:aud":
#                 Ref: IdentityPool
#     Policies:
#       - PolicyName: ${self:custom.role.cognito.unAuth.name}-Policy
#         PolicyDocument:
#           Version: "2012-10-17"
#           Statement:
#             - Effect: "Allow"
#               Action:
#                 - "mobileanalytics:PutEvents"
#                 - "cognito-sync:*"
#               Resource: "*"
#             - Effect: "Allow"
#               Action:
#                 - appsync:GraphQL
#               Resource:
#                 - arn:aws:appsync:${self:provider.region}:${self:custom.account.id}:apis/*/types/Query/fields/getSomething
