EventsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:custom.dynamo.events}
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
  